### PR TITLE
Add no-unreachable:'error' to base config

### PR DESCRIPTION
**Pull request by mtlewis**
Closes #72

### CODE REVIEW

**Comment by SimenB** [comment]
How do we handle these breaking changes?

/cc @userpixel @sveisvei @ivarconr @nosilleg @dlmr @marek-nogiec @andreasrs

**Review by SimenB — APPROVED** [review]
I like it, unsure how to handle breaking changes

**Comment by SimenB** [comment]
I think we should extend eslint:recommended, which includes this rule. That's what we've done at finn

**Comment by nosilleg** [comment]
Also addressed by https://github.com/schibsted/eslint-config-schibsted/pull/74

**Comment by nosilleg** [comment]
Closing as #74 resolved the issue.

**Pull request closed without merging**
