### PR TITLE
Update minimum eslint version

### PR DESCRIPTION
**Pull request by SimenB**
To allow usage of `"error"` instead of `2` in configuration

http://eslint.org/blog/2016/03/eslint-v2.3.0-released#support-for-string-severity-in-configs

eslint-plugin-react is in version 5 as well, btw, could you bump it?

### CODE REVIEW

**Comment by sveisvei** [comment]
@Andersos @nosilleg I think we require more attention to this repo if we should extend it. Should we maybe define some kind of process around usage of this config?

**Comment by nosilleg** [comment]
Hey @SimenB From what I can tell this isn't an obstacle for using the strings in other parts of the config, but it does create an issue for people that are using Eslint < 2.3.  That would be a backward incompatible change and would require a major bump for this project.  As such this isn't something that I would like to do at this time.

With regards to eslint-plugin-react; if the change there doesn't affect the code in this repo then I wouldn't be against a PR that changed the package.json to `>4.x`

@sveisvei Please create an issue with your ideas and we can discuss.

**Comment by SimenB** [comment]
The breaking part of eslint-plugin-react is that, unless you use react@>=15, some deprecation warnings are wrong. You can set a different version, though

Could combine this change with a bump of the react plugin?

**Comment by SimenB** [comment]
It could also be nice to combine that breakage with #9

**Comment by nosilleg** [comment]
#9 seems like it would be non-breaking. (Same end result, just intermediary file) So that doesn't help the cause of this PR.  If we had a branch for next major I'd merge into that, but we don't, and I'm not sure our userbase is appropriate for one. Maybe @andersos is willing to set up a beta next major branch build in npm?

**Comment by SimenB** [comment]
Eslint@3 will release next week (eslint/eslint#6356), we can do this and bump both react plugin and eslint at that time?

**Comment by Andersos** [comment]
We could setup a beta but as @SimenB points out Eslint@3 is close by so I feel it would be a nice idea to bump major for that update as well if we need to do that anyway.

**Comment by nosilleg** [comment]
beta-1 with these changes, beta-2 with eslint@3?

**Comment by SimenB** [comment]
@Andersos @nosilleg Are you interested in PRs for the changes we've made to the FINN config which extends this one? `eslint@3` has been released, so good timing to break something now 😄

**Comment by nosilleg** [comment]
@SimenB Please make a new PR targeted at the v3.0.0 branch.  I'll merge once it's there.

**Comment by SimenB** [comment]
Will do.

**Pull request closed without merging**
