### PR TITLE
Add all changes in the finn repo

### PR DESCRIPTION
**Pull request by SimenB**
I chucked every change in `index` for discussion purposes, a mix of ES6 and ES5 stuff there.

We want to amke ES6 default, and having `finn/es5` disable rules (as in, make ES6 opt-out instead of opt-in). I'll be doing some work on that in the coming days, but for now, everything is in index.

Holler for reasonings, but every change has either a PR or issue [here](https://github.com/finn-no/eslint-config-finn/).

### CODE REVIEW

**Comment by SimenB** [comment]
As discussed, I can open a separate PR for all accepted changes, but as there's a lot of them, an initial huge PR is much less work.

It fails because of the new rules, I'll of course fixup in subsequent PRs.

**Comment by SimenB** [comment]
These are just elint@2 changes as well, will probably update when we can base on eslint@3.

**Comment by SimenB** [comment]
@Andersos @nosilleg News here? Or on a stable v3 release? We're waiting for an open PR for ESlint to be merged, then we'll go stable, would be nice to not depend on a beta 😄

**Comment by nosilleg** [comment]
This PR as-is is to broad in its changes and loosens the rules. Since there hasn't been any additional support for those changes I'm going to close this PR. Feel free to submit smaller ones. Those that do not loosen the rules will likely get quickly merged.

**Pull request closed without merging**
