### PR TITLE
Indent 2. Fix #34

### LINKED ISSUE #34: Indent = 2
The biggest difference between `-schibsted` and `-airbnb` is the indentation.
We [use 2](https://github.com/schibsted/eslint-config-schibsted/blob/master/packages/eslint-config-schibsted/index.js#L78) they [use 2](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L79).

This is a huge stopper for our colleagues who want to move from `-airbnb` to `-schibsted` because this means they practically have to touch most lines of their source code to be compatible with `-schibsted`.

I personally have nothing against *4* and indeed used that in all my previous jobs, but *2* [is all the rage](https://seravo.fi/2013/javascript-the-winning-style) these days. Crockford [recommends 4](http://javascript.crockford.com/code.html), Node [recommends 2](https://github.com/felixge/node-style-guide#2-spaces-for-indentation) but good ol' jQuery goes with [tabs that are 4 characters](https://contribute.jquery.org/style-guide/js/).

Sure when it comes to preferences, choices are as diverse as JavaScript community itself and one can always override the default rules but it would be sweet if we settle for a default that takes minimum effort to migrate the bunch of `-airbnb` based code bases to `-schibsted` as effortlessly as possible.

2 = 👍 4 = 👎. Which 🗳 ?

### PR DESCRIPTION
**Pull request by alexewerlof**
* added a "fix" script to the "package.json" files for quicker local updates with latest rule changes
* updated editor config
* applied indentation-2 to all files

Let's wait with merging this till our colleagues have a say on #34 next week.

### CODE REVIEW

**Comment by alexewerlof** [comment]
since this little change will impose a lot of code change on the client side, should we consider it a "breaking change" and move to 4.x?

**Comment by SimenB** [comment]
This is definitely breaking. We should include it along with other rules from airbnb, to avoid churn

**Review by SimenB — APPROVED** [review]
Should we keep it in a branch? Merging this means we won't be able to do a release (maybe not an issue) until more changes are landed. I really don't think we should release multiple majors over the next couple of weeks

**Comment by alexewerlof** [comment]
> Should we keep it in a branch? Merging this means we won't be able to do a release (maybe not an issue) until more changes are landed. I really don't think we should release multiple majors over the next couple of weeks

So you're suggesting we have a `next` branch to accumulate other possible AirBnB-compatibility rules and then merge all together? If that's the case 👍

**Comment by SimenB** [comment]
Yup, `next` would be perfect!

**Pull request closed without merging**
